# Generated by Django 3.1 on 2020-08-30 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Название категории')),
                ('commit', models.TextField(max_length=1000, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Котегория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('file', models.FileField(upload_to='files/<django.db.models.fields.IntegerField>')),
                ('is_published', models.BooleanField(default=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('commit', models.TextField(max_length=1000, verbose_name='Описание')),
                ('logo', models.ImageField(blank=True, upload_to='forumlogos/', verbose_name='Логотип')),
                ('is_pablished', models.BooleanField(default=True, verbose_name='Публичность')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Forum.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Форум',
                'verbose_name_plural': 'Форумы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('admin', 'Администратор'), ('user', 'Пользователь')], default='user', max_length=150, verbose_name='Группа')),
                ('login', models.CharField(max_length=50, verbose_name='Логин')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('lastname', models.CharField(blank=True, max_length=100, verbose_name='Фамиллия')),
                ('age', models.DateField(blank=True, verbose_name='Дата Рождения')),
                ('photo', models.ImageField(blank=True, upload_to='userphotos/', verbose_name='Фото')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('warn', 'Вынесено предупреждение'), ('block', 'Заблокирован'), ('delate', 'Удален')], default='active', max_length=150, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['login'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('id_forum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Forum.forum', verbose_name='Форум')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Forum.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['create_date'],
            },
        ),
        migrations.AddField(
            model_name='forum',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Forum.user', verbose_name='Создатель'),
        ),
    ]
