# Generated by Django 3.1 on 2020-09-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0002_auto_20200901_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='commit',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
