# Generated by Django 3.1 on 2020-10-05 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0002_auto_20200929_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='id_forum',
            new_name='forum',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='id_user',
            new_name='user',
        ),
    ]
