# Generated by Django 3.1 on 2020-10-18 16:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0009_auto_20201018_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='commit',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='message'),
        ),
    ]
